name: CI-compile

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main
    # instead of "ps2dev/ps2dev:latest" you can use different tags, for example for old projects you can use "ps2dev/ps2dev:v1.0"
    steps:
    - uses: actions/checkout@v4

    - name: Compile project
      run: |
        make
    # commands for compiling your project
        
    # - name: Prepare artifacts
        # zip *.elf
        # create realease archive
        
    - name: Get short SHA and repository name
      id: slug
      run: |
        echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
        echo "::set-output name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"
  
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.slug.outputs.REPOSITORY_NAME }}-${{ steps.slug.outputs.sha8 }}
        path: |
          *.elf
          *.ELF
    # 'path' will create artifact with all *.elf in working directory
    # you can change this

    - name: Create release
      if: github.ref == 'refs/heads/main'
      uses: mathieucarbou/marvinpinto-action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest development build"
        files: |
          *.elf
          *.ELF
    # 'files' will create release with all *.elf in working directory
    # you can change this
 
